version: "3.2"

services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
      - '3306:3306'
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend-1
      - backend-2
  php1:
    build: './serveur1/php/'
    networks:
      - backend-1
    volumes:
      - ./serveur1/html:/usr/local/apache2/htdocs/
  serveur1:
    image: httpd:latest
    networks:
      - backend-1
    volumes:
      - ./serveur1/html/:/usr/local/apache2/htdocs/
      - ./serveur1/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  mariadb1:
    image: mariadb
    networks:
      - backend-1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata_serveur1:/var/lib/mysql
  php2:
    build: './serveur2/php/'
    networks:
      - backend-2
    volumes:
      - ./serveur2/html:/usr/local/apache2/htdocs/
  serveur2:
    image: httpd:latest
    networks:
      - backend-2
    volumes:
      - ./serveur2/html/:/usr/local/apache2/htdocs/
      - ./serveur2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  mariadb2:
    image: mariadb
    networks:
      - backend-2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata_serveur2:/var/lib/mysql
networks:
  frontend:
  backend-1:
  backend-2:
volumes:
  dbdata_serveur1:
  dbdata_serveur2:
